### ISSUE TITLE
Can we talk once about Linux?

### ISSUE THREAD

**Issue by thegarvitrai** [dibyabiva/MSI-Modern-14-B4MW-Fan-Curve-Controller#1]
Hey Dibyabiva

I'm facing some issues with Ubuntu on MSI Modern 14 B4MW. I was wondering if you'd be able to help me in that please
It would be really helpful, my internship depends on it

**Comment by dibyabiva** [comment]
Hi, what seems to be the issue?

**Comment by thegarvitrai** [comment]
I'm getting a lot of file blocks/super blocks in my system out of nowhere, at least once a day & don't know whats the reason behind it
It crashed the system after it & requires fsck & reinstalling GRUB too. Do you happened to face this too with your laptop?

**Comment by dibyabiva** [comment]
Did you recently upgrade to Ubuntu 22.04? If so, please go back to Ubuntu 20.04.

There are some compatibility issues between Ubuntu 22.04 and this laptop. I've faced it too, and currently the only way to resolve this is to go back to Ubuntu 20.04

**Comment by thegarvitrai** [comment]
I did, I'm using 22.04. Thanks for this dude I'll switch back to 20.04 now

Do you have any socials like Insta or Twitter you use?

**Comment by dibyabiva** [comment]
Happy to be of help. And I don't have any social media accounts, not a fan :sweat_smile:
